require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sections", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Section. As you add validations to Section, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Section.create! valid_attributes
      get sections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      section = Section.create! valid_attributes
      get section_url(section)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_section_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      section = Section.create! valid_attributes
      get edit_section_url(section)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Section" do
        expect {
          post sections_url, params: { section: valid_attributes }
        }.to change(Section, :count).by(1)
      end

      it "redirects to the created section" do
        post sections_url, params: { section: valid_attributes }
        expect(response).to redirect_to(section_url(Section.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Section" do
        expect {
          post sections_url, params: { section: invalid_attributes }
        }.to change(Section, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sections_url, params: { section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested section" do
        section = Section.create! valid_attributes
        patch section_url(section), params: { section: new_attributes }
        section.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the section" do
        section = Section.create! valid_attributes
        patch section_url(section), params: { section: new_attributes }
        section.reload
        expect(response).to redirect_to(section_url(section))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        section = Section.create! valid_attributes
        patch section_url(section), params: { section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested section" do
      section = Section.create! valid_attributes
      expect {
        delete section_url(section)
      }.to change(Section, :count).by(-1)
    end

    it "redirects to the sections list" do
      section = Section.create! valid_attributes
      delete section_url(section)
      expect(response).to redirect_to(sections_url)
    end
  end
end
